### ISSUE TITLE
Rebuild kernel using AOSP December update to fix ADB and bootup time when booted via `fastboot boot`

### ISSUE THREAD

**Issue by zhuowei** [TeamWin/android_device_google_crosshatch#1]
There's two known issues with TWRP on the Pixel 3 XL (as [documented](https://twrp.me/google/googlepixel3xl.html) on the TWRP downloads page):

- USB doesn't work when booted via fastboot
- boot takes forever when booted via fastboot

I did an experiment: it turns out both problems are caused by the outdated kernel in TWRP. Replacing the kernel with the stock kernel from the December factory image fixes these issues.

TWRP currently ships a kernel built from the initial AOSP kernel release (the September update).

I binary patched a newer stock kernel (from the December factory image) to always load the initramfs, recompressed TWRP ramdisk (since stock kernel uses Gzip) and [rebuilt the bootimg](https://drive.google.com/file/d/1XgJe6O5F83LeoBF9k20xnzrzjPAHy0Hc/view?usp=sharing).

Result: when `fastboot boot`ed on a Pixel 3 XL (running December update on the active B slot):

- USB works (tested `adb shell`).
- TWRP boots immediately.

(the touchscreen doesn't work since the stock kernel enforces module signing. A TWRP-built kernel probably won't have this issue.)

I hope you can consider rebuilding TWRP's kernel to fix ADB support through Fastboot, as on previous devices pulling logs by fastbooting into TWRP was super helpful. I'll be happy to help or to test any new builds.

Thank you so much for the amazing work on TWRP.

**Comment by bigbiff** [comment]
Fixed in 3.2.3-3.

**Comment by zhuowei** [comment]
Thank you so much!

**Comment by zhuowei** [comment]
@bigbiff Tested on Pixel 3 XL with the December system image in the active slot: adb works and the boot time is short when using `fastboot boot twrp-3.2.3-3-crosshatch.img`.

Thank you so much!
