### ISSUE TITLE
crosshatch on Android Q Beta 5 cannot mount partitions 

### ISSUE THREAD

**Issue by moldimolt** [TeamWin/android_device_google_crosshatch#3]
This is a repost of [Team-Win-Recovery-Project:#1486](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1486) here since it is a device specific issue (though, likely effects crosshatch, blueline, bonito, and sargo - all the Pixel 3 series devices).

**Device codename:** crosshatch
**TWRP version:** twrp-3.3.1-2-crosshatch.img

### WHAT STEPS WILL REPRODUCE THE PROBLEM?
1. Boot phone into bootloader
1. `fastboot boot twrp-3.3.1-2-crosshatch.img`
1. After booting into TWRP, select 'Mount'

### WHAT IS THE EXPECTED RESULT?
Partitions like System, Data, Storage should be mountable by ticking the checkmark.

### WHAT HAPPENS INSTEAD?
1. Only metadata partitions are pre-checked; all other partitions (System, Data, Storage...) are not checkable. (Even if you try to check it, a check mark will not appear and the partition will not be mounted). 
1. Attempting to mount with `adb sideload` or similar gives "invalid argument".

### ADDITIONAL INFORMATION
```
adb mount shows:
crosshatch:/ # mount
rootfs on / type rootfs (rw,seclabel,size=1690556k,nr_inodes=422639)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=1803612k,nr_inodes=450903,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600,ptmxmode=000)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
sysfs on /sys type sysfs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=1803612k,nr_inodes=450903,mode=755,gid=1000)
none on /acct type cgroup (rw,relatime,cpuacct)
tmpfs on /tmp type tmpfs (rw,seclabel,relatime,size=1803612k,nr_inodes=450903)
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
none on /config type configfs (rw,relatime)
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
mtp on /dev/usb-ffs/mtp type functionfs (rw,relatime)
ptp on /dev/usb-ffs/ptp type functionfs (rw,relatime)
/dev/block/sda20 on /metadata type ext4 (rw,seclabel,relatime,data=ordered)
```

**Attachments:**
* [recovery.log](https://github.com/TeamWin/android_device_google_crosshatch/files/3453225/recovery.log)
* [twrpdmesg.txt](https://github.com/TeamWin/android_device_google_crosshatch/files/3453226/twrpdmesg.txt)
* [twrppartitions.txt](https://github.com/TeamWin/android_device_google_crosshatch/files/3453228/twrppartitions.txt)

**Comment by bigbiff** [comment]
Duplicate.
