### ISSUE TITLE
Pixel 3 blueline Android 11 Beta 3 doesn't boot (Invalid Parameter)

### ISSUE THREAD

**Issue by ih8ms** [TeamWin/android_device_google_crosshatch#5]
I'm running Android 11 Beta 3 on my Pixel 3.

Trying to boot twrp-3.3.0-0-blueline.img, I get this:

```fastboot boot twrp-3.3.0-0-blueline.img 
Sending 'boot.img' (65536 KB)                      OKAY [  2.190s]
Booting                                            FAILED (remote: 'Error verifying the received boot.img: Invalid Parameter')
fastboot: error: Command failed```

**Comment by ian5142** [comment]
I have the same problem with the latest Google Android 11 build (Jan 5 2021). I just received my Pixel 3 (blueline). Can't fastboot boot twrp 3.3.0 on it. Fastboot can find the device. Same error as above.

**Comment by bigbiff** [comment]
android 11 is not supported yet.
